import type { CardRowForScoring } from "@/lib/recommendV2/scoring";

/**
 * Small deterministic catalog for local dev / tests.
 * Replace with `candidatesOverride` from your API (e.g. Supabase) in production.
 */
export const MOCK_CANDIDATE_CARDS: CardRowForScoring[] = [
  {
    id: "mock-axis-flipkart",
    card_name: "Flipkart Axis Bank Credit Card",
    bank: "Axis Bank",
    joining_fee: 500,
    annual_fee: 500,
    reward_type: "cashback",
    reward_rate: "5% on Flipkart; 4% on preferred merchants; 1.5% elsewhere",
    lounge_access: "None",
    best_for: "Online shopping on Flipkart and Myntra",
    key_benefits: "Unlimited cashback; dining offers",
    dining_reward: 4,
    travel_reward: 2,
    shopping_reward: 5,
    fuel_reward: 1,
    network: "Visa",
    metadata: null,
  },
  {
    id: "mock-hdfc-diners",
    card_name: "HDFC Diners Club Black",
    bank: "HDFC Bank",
    joining_fee: 10000,
    annual_fee: 10000,
    reward_type: "points",
    reward_rate: "3.33% on most spends; 10X partners",
    lounge_access: "Unlimited international lounge via Priority Pass",
    best_for: "Travel and premium lifestyle",
    key_benefits: "International lounge; golf; concierge",
    dining_reward: 3,
    travel_reward: 6,
    shopping_reward: 3,
    fuel_reward: 1,
    network: "Diners",
    metadata: null,
  },
  {
    id: "mock-sbi-prime",
    card_name: "SBI Card PRIME",
    bank: "SBI Card",
    joining_fee: 2999,
    annual_fee: 2999,
    reward_type: "points",
    reward_rate: "5X on dining, groceries, movies",
    lounge_access: "Domestic lounge 4 visits/year",
    best_for: "Dining and utility bill payments",
    key_benefits: "Movie tickets; domestic lounge",
    dining_reward: 5,
    travel_reward: 2,
    shopping_reward: 2,
    fuel_reward: 3,
    network: "Visa",
    metadata: null,
  },
  {
    id: "mock-icici-amazon",
    card_name: "Amazon Pay ICICI Credit Card",
    bank: "ICICI Bank",
    joining_fee: 0,
    annual_fee: 0,
    reward_type: "cashback",
    reward_rate: "5% on Amazon for Prime members; 3% Amazon non-Prime; 1% elsewhere",
    lounge_access: "None",
    best_for: "Amazon shoppers",
    key_benefits: "Lifetime free; simple cashback",
    dining_reward: 2,
    travel_reward: 1,
    shopping_reward: 5,
    fuel_reward: 1,
    network: "Visa",
    metadata: null,
  },
  {
    id: "mock-amex-mrcc",
    card_name: "American Express Membership Rewards",
    bank: "American Express",
    joining_fee: 0,
    annual_fee: 1500,
    reward_type: "points",
    reward_rate: "1 MR per ₹40; accelerated on select categories",
    lounge_access: "None",
    best_for: "Reward points collectors",
    key_benefits: "Transfer partners; milestone bonuses",
    dining_reward: 2,
    travel_reward: 2,
    shopping_reward: 2,
    fuel_reward: 1,
    network: "Amex",
    metadata: null,
  },
  {
    id: "mock-indusind-iconia",
    card_name: "IndusInd Bank Pinnacle Credit Card",
    bank: "IndusInd Bank",
    joining_fee: 0,
    annual_fee: 12000,
    reward_type: "points",
    reward_rate: "2.5% on weekend dining; travel benefits",
    lounge_access: "International lounge Priority Pass",
    best_for: "Weekend dining and travel",
    key_benefits: "International lounge; travel insurance",
    dining_reward: 6,
    travel_reward: 4,
    shopping_reward: 2,
    fuel_reward: 1,
    network: "Mastercard",
    metadata: null,
  },
];
