import { NextResponse } from "next/server";
import { getOptionalCardNetworkFilter } from "@/lib/cards/networkFilter";
import { areThirdPartyApisDisabled } from "@/lib/config/externalAccess";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import type { CardNetwork } from "@/lib/types/card";

type RecommendWithAiRequest = {
  monthly_spend: number;
  categories: string[];
};

type CreditCardRow = {
  id: string;
  card_name: string;
  bank: string;
  network: CardNetwork;
  annual_fee: number;
  reward_type: "cashback" | "points";
  reward_rate: string | null;
  lounge_access: string | null;
  best_for: string | null;
  key_benefits: string | null;
};

type AiRecommendation = {
  card_id: string;
  card_name: string;
  reason: string;
};

function validateBody(body: RecommendWithAiRequest): string | null {
  if (typeof body.monthly_spend !== "number" || body.monthly_spend <= 0) {
    return "monthly_spend must be a positive number.";
  }
  if (!Array.isArray(body.categories) || body.categories.length === 0) {
    return "categories must be a non-empty array of strings.";
  }
  if (body.categories.some((category) => typeof category !== "string")) {
    return "categories must contain only strings.";
  }
  return null;
}

function buildPrompt(profile: RecommendWithAiRequest, cards: CreditCardRow[]): string {
  return `
You are a credit card recommendation assistant.

User profile:
- Monthly spend (INR): ${profile.monthly_spend}
- Spending categories: ${profile.categories.join(", ")}

Credit cards JSON:
${JSON.stringify(cards)}

Task:
- Pick the best 2 cards for this user.
- Rank by likely reward fit and practical fee value.
- Prefer cards where best_for/reward_rate aligns with categories.
- Consider annual_fee versus monthly_spend.

Return ONLY valid JSON in this exact format:
{
  "recommendations": [
    {
      "card_id": "uuid",
      "card_name": "string",
      "reason": "concise reason tied to profile"
    }
  ]
}
`.trim();
}

export async function POST(request: Request) {
  try {
    if (areThirdPartyApisDisabled()) {
      return NextResponse.json(
        {
          error:
            "External API calls are disabled (DISABLE_EXTERNAL_API_CALLS).",
        },
        { status: 503 }
      );
    }
    const body = (await request.json()) as RecommendWithAiRequest;
    const validationError = validateBody(body);
    if (validationError) {
      return NextResponse.json({ error: validationError }, { status: 400 });
    }

    const supabase = getSupabaseServerClient();
    const envNetwork = getOptionalCardNetworkFilter();
    let cardsQuery = supabase
      .from("credit_cards")
      .select(
        "id, card_name, bank, network, annual_fee, reward_type, reward_rate, lounge_access, best_for, key_benefits"
      )
      .order("annual_fee", { ascending: true })
      .limit(100);
    if (envNetwork) {
      cardsQuery = cardsQuery.eq("network", envNetwork);
    }
    const { data: cards, error: cardsError } = await cardsQuery;

    if (cardsError) {
      throw new Error(cardsError.message);
    }
    if (!cards || cards.length === 0) {
      return NextResponse.json(
        { error: "No credit cards found in database." },
        { status: 404 }
      );
    }

    const openaiApiKey = process.env.OPENAI_API_KEY;
    if (!openaiApiKey) {
      return NextResponse.json(
        { error: "Missing OPENAI_API_KEY environment variable." },
        { status: 500 }
      );
    }

    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${openaiApiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        temperature: 0.2,
        response_format: { type: "json_object" },
        messages: [
          {
            role: "system",
            content:
              "Return strict JSON only. Recommend top credit cards based on user profile.",
          },
          { role: "user", content: buildPrompt(body, cards as CreditCardRow[]) },
        ],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`OpenAI API error: ${errorText}`);
    }

    const llmResult = (await response.json()) as {
      choices?: Array<{ message?: { content?: string } }>;
    };
    const content = llmResult.choices?.[0]?.message?.content;
    if (!content) {
      throw new Error("OpenAI returned empty response.");
    }

    const parsed = JSON.parse(content) as {
      recommendations?: AiRecommendation[];
    };
    const top2 = (parsed.recommendations ?? []).slice(0, 2);

    if (top2.length === 0) {
      return NextResponse.json(
        { error: "No recommendations generated by AI." },
        { status: 502 }
      );
    }

    return NextResponse.json(
      {
        input: body,
        recommendations: top2,
      },
      { status: 200 }
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unexpected error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
